/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.ac.tuwien.dsg.userinterface;

import at.ac.tuwien.dsg.servicedemandmodel.ResultQuality;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anindita
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        analyticCostTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        analyticTimeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        completenessTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        processTypeTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        uriTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        objectNameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        processedDataTypeTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        consistencyTextField = new javax.swing.JTextField();
        reliabilityTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        accuracyTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Information about QUALITY OF RESULT");

        jLabel2.setText("Analytic Cost (euro/MB):");

        analyticCostTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                analyticCostTextFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("Analytic Time (sec/MB):");

        analyticTimeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                analyticTimeTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("Completeness (%):");

        completenessTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                completenessTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Consistency (%):");

        processTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processTypeTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("URI:");

        uriTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uriTextFieldMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("e.g., www.DataAnalyticServiceDemand.com");
        jLabel7.setToolTipText("e.g., www.DataAnalyticServiceDemand.com");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel8.setText("Object Name:");

        objectNameTextField.setToolTipText("DataAnalyticServiceDemand");
        objectNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                objectNameTextFieldMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 102, 102));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 204));
        jLabel9.setText("e.g., DataAnalyticServiceDemand");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));

        jLabel10.setText("Information about identifier:");

        jLabel11.setText("Information about data analytic services:");

        jLabel12.setText("Processed Data Type:");

        jLabel13.setText("Information about Data Quality:");

        jLabel14.setText("Processes Type:");

        jLabel15.setText("Reliability (%):");

        consistencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consistencyTextFieldActionPerformed(evt);
            }
        });
        consistencyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consistencyTextFieldKeyTyped(evt);
            }
        });

        reliabilityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reliabilityTextFieldKeyTyped(evt);
            }
        });

        jLabel16.setText("Accuracy (%):");

        accuracyTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accuracyTextFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(analyticTimeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(analyticCostTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(processedDataTypeTextField))
                            .addComponent(processTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consistencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(completenessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(uriTextField)
                                    .addComponent(objectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(reliabilityTextField)
                                    .addComponent(accuracyTextField))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(objectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(analyticCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(analyticTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(processedDataTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(processTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(completenessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5))
                            .addComponent(consistencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reliabilityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accuracyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analyticCostTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_analyticCostTextFieldKeyTyped
char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      }         
    }//GEN-LAST:event_analyticCostTextFieldKeyTyped

    private void analyticTimeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_analyticTimeTextFieldKeyTyped
        char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      } 
    }//GEN-LAST:event_analyticTimeTextFieldKeyTyped

    private void completenessTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_completenessTextFieldKeyTyped
char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      }          
    }//GEN-LAST:event_completenessTextFieldKeyTyped

    private void uriTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uriTextFieldMouseClicked
uriTextField.setText("www.DataAnalyticServiceDemand.com");        
    }//GEN-LAST:event_uriTextFieldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 JFrame frame=new JFrame("test");
       HashMap information=new HashMap();
       //information.put("taskNumber", new String(completenessTextField.getText()));
       information.put("processType", new String(processTypeTextField.getText()));
       information.put("analyticCost", new String(analyticCostTextField.getText()+"euro/MB"));
       information.put("analyticTime", new String(analyticTimeTextField.getText()+"sec/MB"));
       information.put("processedDataType", new String(processedDataTypeTextField.getText()));
       information.put("completeness", new String(completenessTextField.getText()+"%"));
       information.put("consistency", new String(consistencyTextField.getText()+"%"));
       information.put("reliability", new String(reliabilityTextField.getText()+"%"));
       information.put("accuracy", new String(accuracyTextField.getText()+"%"));
       if(uriTextField.getText().isEmpty()) 
       {
           JOptionPane.showMessageDialog(frame, "You should enter the value of URI","Warning Message", JOptionPane.WARNING_MESSAGE);
       }
       else{ 
        
           ResultQuality.uri="http://"+uriTextField.getText()+"#";
           ResultQuality.objectName=objectNameTextField.getText();
           ResultQuality.getInstance().modelCreation(information); 
       
           JOptionPane.showMessageDialog(frame, "The generated "+objectNameTextField.getText()+".rdf file is stored in ./example folder ");
       }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void objectNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_objectNameTextFieldMouseClicked
objectNameTextField.setText("DataAnalyticServiceDemand");        // TODO add your handling code here:
    }//GEN-LAST:event_objectNameTextFieldMouseClicked

    private void processTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processTypeTextFieldActionPerformed

    private void consistencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consistencyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consistencyTextFieldActionPerformed

    private void consistencyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consistencyTextFieldKeyTyped
        char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      }     // TODO add your handling code here:
    }//GEN-LAST:event_consistencyTextFieldKeyTyped

    private void reliabilityTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reliabilityTextFieldKeyTyped
char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      }             // TODO add your handling code here:
    }//GEN-LAST:event_reliabilityTextFieldKeyTyped

    private void accuracyTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accuracyTextFieldKeyTyped
char c=evt.getKeyChar();
      if(! (Character.isDigit(c) || (c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_BACK_SPACE)))
        {
         getToolkit().beep();
          evt.consume();
      
      }             // TODO add your handling code here:
    }//GEN-LAST:event_accuracyTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accuracyTextField;
    private javax.swing.JTextField analyticCostTextField;
    private javax.swing.JTextField analyticTimeTextField;
    private javax.swing.JTextField completenessTextField;
    private javax.swing.JTextField consistencyTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField objectNameTextField;
    private javax.swing.JTextField processTypeTextField;
    private javax.swing.JTextField processedDataTypeTextField;
    private javax.swing.JTextField reliabilityTextField;
    private javax.swing.JTextField uriTextField;
    // End of variables declaration//GEN-END:variables
}
